function slugifyClubName(name) {
  return name
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/&/g, 'and')
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase();
}

const premierLeague = [
  'Arsenal',
  'Aston Villa',
  'Bournemouth',
  'Brentford',
  'Brighton & Hove Albion',
  'Burnley',
  'Chelsea',
  'Crystal Palace',
  'Everton',
  'Fulham',
  'Leeds United',
  'Liverpool',
  'Manchester City',
  'Manchester United',
  'Newcastle United',
  'Nottingham Forest',
  'Sunderland',
  'Tottenham Hotspur',
  'West Ham United',
  'Wolverhampton Wanderers',
];

const laLiga = [
  'Athletic Club',
  'Atletico Madrid',
  'Barcelona',
  'Girona',
  'Rayo Vallecano',
  'Real Betis',
  'Real Madrid',
  'Real Sociedad',
  'Sevilla',
  'Valencia',
  'Villarreal',
];

const bundesliga = [
  'Bayer Leverkusen',
  'Bayern Munich',
  'Borussia Dortmund',
  'Borussia Monchengladbach',
  'Eintracht Frankfurt',
  'Hamburger SV',
  'RB Leipzig',
  'Werder Bremen',
  'Wolfsburg',
  'Stuttgart',
];

const serieA = [
  'Atalanta',
  'Como',
  'Fiorentina',
  'Inter Milan',
  'Juventus',
  'Lazio',
  'AC Milan',
  'Napoli',
  'Roma',
  'Sassuolo',
  'Torino',
  'Udinese',
];

const ligue1 = [
  'Lille',
  'Lyon',
  'Marseille',
  'Monaco',
  'Nice',
  'Paris Saint-Germain',
  'Rennes',
  'Toulouse',
];

const superLig = [
  'Alanyaspor',
  'Antalyaspor',
  'Basaksehir',
  'Besiktas',
  'Eyupspor',
  'Fatih Karagumruk',
  'Fenerbahce',
  'Galatasaray',
  'Gaziantep FK',
  'Genclerbirligi',
  'Goztepe',
  'Kasimpasa',
  'Kayserispor',
  'Kocaelispor',
  'Konyaspor',
  'Rizespor',
  'Samsunspor',
  'Trabzonspor',
];

const extraClubs = ['Ajax', 'Benfica', 'Sporting CP', 'PSV Eindhoven', 'Flamengo', 'Santos'];

const europeCountries = [
  ['Albania', 'al'],
  ['Armenia', 'am'],
  ['Austria', 'at'],
  ['Azerbaijan', 'az'],
  ['Belgium', 'be'],
  ['Bosnia and Herzegovina', 'ba'],
  ['Bulgaria', 'bg'],
  ['Croatia', 'hr'],
  ['Czechia', 'cz'],
  ['Denmark', 'dk'],
  ['France', 'fr'],
  ['Georgia', 'ge'],
  ['Germany', 'de'],
  ['Greece', 'gr'],
  ['Hungary', 'hu'],
  ['Ireland', 'ie'],
  ['Italy', 'it'],
  ['Netherlands', 'nl'],
  ['Norway', 'no'],
  ['Poland', 'pl'],
  ['Portugal', 'pt'],
  ['Romania', 'ro'],
  ['Serbia', 'rs'],
  ['Slovakia', 'sk'],
  ['Slovenia', 'si'],
  ['Spain', 'es'],
  ['Sweden', 'se'],
  ['Switzerland', 'ch'],
  ['Turkey', 'tr'],
  ['Ukraine', 'ua'],
  ['England', 'gb-eng'],
];

const africaCountries = [
  ['Algeria', 'dz'],
  ['Cameroon', 'cm'],
  ['Egypt', 'eg'],
  ['Gabon', 'ga'],
  ['Ghana', 'gh'],
  ['Ivory Coast', 'ci'],
  ['Morocco', 'ma'],
  ['Nigeria', 'ng'],
  ['Senegal', 'sn'],
  ['Togo', 'tg'],
];

const northAmericaCountries = [
  ['Canada', 'ca'],
  ['Jamaica', 'jm'],
  ['Mexico', 'mx'],
  ['United States', 'us'],
];

const southAmericaCountries = [
  ['Argentina', 'ar'],
  ['Brazil', 'br'],
  ['Chile', 'cl'],
  ['Colombia', 'co'],
  ['Ecuador', 'ec'],
  ['Uruguay', 'uy'],
];

const clubHomeCountryMap = new Map([
  ...premierLeague.map((team) => [team, 'England']),
  ...laLiga.map((team) => [team, 'Spain']),
  ...bundesliga.map((team) => [team, 'Germany']),
  ...serieA.map((team) => [team, 'Italy']),
  ...ligue1.map((team) => [team, 'France']),
  ...superLig.map((team) => [team, 'Turkey']),
  ['Ajax', 'Netherlands'],
  ['PSV Eindhoven', 'Netherlands'],
  ['Benfica', 'Portugal'],
  ['Sporting CP', 'Portugal'],
  ['Flamengo', 'Brazil'],
  ['Santos', 'Brazil'],
]);

export function getClubHomeCountry(clubName) {
  return clubHomeCountryMap.get(clubName) ?? null;
}

const clubLeagueMap = new Map([
  ...premierLeague.map((team) => [team, 'Premier League']),
  ...laLiga.map((team) => [team, 'LaLiga']),
  ...bundesliga.map((team) => [team, 'Bundesliga']),
  ...serieA.map((team) => [team, 'Serie A']),
  ...ligue1.map((team) => [team, 'Ligue 1']),
  ...superLig.map((team) => [team, 'Trendyol Süper Lig']),
  ['Ajax', 'Ek Kulüp'],
  ['Benfica', 'Ek Kulüp'],
  ['Sporting CP', 'Ek Kulüp'],
  ['PSV Eindhoven', 'Ek Kulüp'],
  ['Flamengo', 'Ek Kulüp'],
  ['Santos', 'Ek Kulüp'],
]);

const clubDisplayNameMap = new Map([
  ['Arsenal', 'Arsenal'],
  ['Aston Villa', 'Aston Villa'],
  ['Bournemouth', 'Bournemouth'],
  ['Brentford', 'Brentford'],
  ['Brighton & Hove Albion', 'Brighton & Hove Albion'],
  ['Burnley', 'Burnley'],
  ['Chelsea', 'Chelsea'],
  ['Crystal Palace', 'Crystal Palace'],
  ['Everton', 'Everton'],
  ['Fulham', 'Fulham'],
  ['Leeds United', 'Leeds United'],
  ['Liverpool', 'Liverpool'],
  ['Manchester City', 'Manchester City'],
  ['Manchester United', 'Manchester United'],
  ['Newcastle United', 'Newcastle United'],
  ['Nottingham Forest', 'Nottingham Forest'],
  ['Sunderland', 'Sunderland'],
  ['Tottenham Hotspur', 'Tottenham Hotspur'],
  ['West Ham United', 'West Ham United'],
  ['Wolverhampton Wanderers', 'Wolverhampton Wanderers'],
  ['Athletic Club', 'Athletic Bilbao'],
  ['Atletico Madrid', 'Atletico Madrid'],
  ['Barcelona', 'Barcelona'],
  ['Girona', 'Girona'],
  ['Rayo Vallecano', 'Rayo Vallecano'],
  ['Real Betis', 'Real Betis'],
  ['Real Madrid', 'Real Madrid'],
  ['Real Sociedad', 'Real Sociedad'],
  ['Sevilla', 'Sevilla'],
  ['Valencia', 'Valencia'],
  ['Villarreal', 'Villarreal'],
  ['Bayer Leverkusen', 'Bayer Leverkusen'],
  ['Bayern Munich', 'Bayern Munih'],
  ['Borussia Dortmund', 'Borussia Dortmund'],
  ['Borussia Monchengladbach', 'Borussia Monchengladbach'],
  ['Eintracht Frankfurt', 'Eintracht Frankfurt'],
  ['Hamburger SV', 'Hamburger SV'],
  ['RB Leipzig', 'RB Leipzig'],
  ['Werder Bremen', 'Werder Bremen'],
  ['Wolfsburg', 'Wolfsburg'],
  ['Stuttgart', 'Stuttgart'],
  ['Atalanta', 'Atalanta'],
  ['Como', 'Como'],
  ['Fiorentina', 'Fiorentina'],
  ['Inter Milan', 'Inter'],
  ['Juventus', 'Juventus'],
  ['Lazio', 'Lazio'],
  ['AC Milan', 'Milan'],
  ['Napoli', 'Napoli'],
  ['Roma', 'Roma'],
  ['Sassuolo', 'Sassuolo'],
  ['Torino', 'Torino'],
  ['Udinese', 'Udinese'],
  ['Lille', 'Lille'],
  ['Lyon', 'Lyon'],
  ['Marseille', 'Marsilya'],
  ['Monaco', 'Monaco'],
  ['Nice', 'Nice'],
  ['Paris Saint-Germain', 'Paris Saint-Germain'],
  ['Rennes', 'Rennes'],
  ['Toulouse', 'Toulouse'],
  ['Alanyaspor', 'Alanyaspor'],
  ['Antalyaspor', 'Antalyaspor'],
  ['Basaksehir', 'Başakşehir'],
  ['Besiktas', 'Beşiktaş'],
  ['Eyupspor', 'Eyüpspor'],
  ['Fatih Karagumruk', 'Fatih Karagümrük'],
  ['Fenerbahce', 'Fenerbahçe'],
  ['Galatasaray', 'Galatasaray'],
  ['Gaziantep FK', 'Gaziantep FK'],
  ['Genclerbirligi', 'Gençlerbirliği'],
  ['Goztepe', 'Göztepe'],
  ['Kasimpasa', 'Kasımpaşa'],
  ['Kayserispor', 'Kayserispor'],
  ['Kocaelispor', 'Kocaelispor'],
  ['Konyaspor', 'Konyaspor'],
  ['Rizespor', 'Rizespor'],
  ['Samsunspor', 'Samsunspor'],
  ['Trabzonspor', 'Trabzonspor'],
  ['Ajax', 'Ajax'],
  ['Benfica', 'Benfica'],
  ['Sporting CP', 'Sporting Lizbon'],
  ['PSV Eindhoven', 'PSV Eindhoven'],
  ['Flamengo', 'Flamengo'],
  ['Santos', 'Santos'],
]);

const countryDisplayNameMap = new Map([
  ['Albania', 'Arnavutluk'],
  ['Armenia', 'Ermenistan'],
  ['Austria', 'Avusturya'],
  ['Azerbaijan', 'Azerbaycan'],
  ['Belgium', 'Belçika'],
  ['Bosnia and Herzegovina', 'Bosna Hersek'],
  ['Bulgaria', 'Bulgaristan'],
  ['Croatia', 'Hırvatistan'],
  ['Czechia', 'Çekya'],
  ['Denmark', 'Danimarka'],
  ['France', 'Fransa'],
  ['Georgia', 'Gürcistan'],
  ['Germany', 'Almanya'],
  ['Greece', 'Yunanistan'],
  ['Hungary', 'Macaristan'],
  ['Ireland', 'İrlanda'],
  ['Italy', 'İtalya'],
  ['Netherlands', 'Hollanda'],
  ['Norway', 'Norveç'],
  ['Poland', 'Polonya'],
  ['Portugal', 'Portekiz'],
  ['Romania', 'Romanya'],
  ['Serbia', 'Sırbistan'],
  ['Slovakia', 'Slovakya'],
  ['Slovenia', 'Slovenya'],
  ['Spain', 'İspanya'],
  ['Sweden', 'İsveç'],
  ['Switzerland', 'İsviçre'],
  ['Turkey', 'Türkiye'],
  ['Ukraine', 'Ukrayna'],
  ['England', 'İngiltere'],
  ['Algeria', 'Cezayir'],
  ['Cameroon', 'Kamerun'],
  ['Egypt', 'Mısır'],
  ['Gabon', 'Gabon'],
  ['Ghana', 'Gana'],
  ['Ivory Coast', 'Fildişi Sahili'],
  ['Morocco', 'Fas'],
  ['Nigeria', 'Nijerya'],
  ['Senegal', 'Senegal'],
  ['Togo', 'Togo'],
  ['Canada', 'Kanada'],
  ['Jamaica', 'Jamaika'],
  ['Mexico', 'Meksika'],
  ['United States', 'Amerika Birleşik Devletleri'],
  ['Argentina', 'Arjantin'],
  ['Brazil', 'Brezilya'],
  ['Chile', 'Şili'],
  ['Colombia', 'Kolombiya'],
  ['Ecuador', 'Ekvador'],
  ['Uruguay', 'Uruguay'],
]);

const leagueDisplayNameMap = new Map([
  ['Premier League', 'Premier League'],
  ['LaLiga', 'LaLiga'],
  ['Bundesliga', 'Bundesliga'],
  ['Serie A', 'Serie A'],
  ['Ligue 1', 'Ligue 1'],
  ['Trendyol Süper Lig', 'Trendyol Süper Lig'],
  ['Ek Kulüp', 'Ek Kulüp'],
]);

export const clubs = [...new Set([...premierLeague, ...laLiga, ...bundesliga, ...serieA, ...ligue1, ...superLig, ...extraClubs])].map(
  (name) => ({
    name,
    displayName: clubDisplayNameMap.get(name) ?? name,
    slug: slugifyClubName(name),
    league: clubLeagueMap.get(name) ?? 'Kulup',
    leagueDisplayName: leagueDisplayNameMap.get(clubLeagueMap.get(name) ?? 'Kulup') ?? 'Kulup',
    type: 'club',
    localLogoPath: `./assets/logos/clubs/${slugifyClubName(name)}.png`,
  }),
);

export const countries = [
  ...europeCountries,
  ...africaCountries,
  ...northAmericaCountries,
  ...southAmericaCountries,
].map(([name, code]) => ({
  name,
  displayName: countryDisplayNameMap.get(name) ?? name,
  code,
  type: 'country',
}));